---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: sharefolio
description: Sharefolio Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: staging
  - targetId: production
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/sharefolio-359221/locations/northamerica-northeast1/clusters/staging
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: Production Environment
gke:
  cluster: projects/sharefolio-359221/locations/northamerica-northeast1/clusters/production
